app:
  version: 3.0.0-beta.12
  enableCheckDigitConv: ${CHECK_DIGIT_CONVERSION:false}
  patient-id-pattern: "[^0]\\d{8}"

fhir:
  profiles:
    histologie: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Histologie"
    grading: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Grading"
    tnmC: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TNMc"
    tnmP: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TNMp"
    fernMeta: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-Fernmetastasen"
    condition: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Condition-Primaerdiagnose"
    genVariante: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-GenetischeVariante"
    opProcedure: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Procedure-Operation"
    stProcedure: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Procedure-Strahlentherapie"
    systMedStatement: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-MedicationStatement-Systemtherapie"
    deathObservation: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Observation-TodUrsache"
    miiPrOnkoGrading: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-grading"
    # MII
    # renovate: datasource=npm depName=@mii-termserv/de.medizininformatikinitiative.kerndatensatz.terminology.person
    mii-person-package-version: 2025.0.0-alpha.2
    mii-patient-pseudonymisiert: "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert|${fhir.profiles.mii-person-package-version}"
    # renovate: datasource=npm depName=react
    mii-onko-package-version: 18.3.0
    mii-pr-onko-operation: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-operation|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-diagnose-primaertumor: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-diagnose-primaertumor|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-strahlentherapie: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-strahlentherapie|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-fernmetastasen: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-fernmetastasen|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-systemische-therapie: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-systemische-therapie|${fhir.profiles.mii-onko-package-version}"
    mii-pr-medication-statement: "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-specimen: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-specimen|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-anzahl-befallene-lymphknoten: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-anzahl-befallene-lymphknoten|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-anzahl-befallene-sentinel-lymphknoten: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-anzahl-befallene-sentinel-lymphknoten|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-anzahl-untersuchte-lymphknoten: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-anzahl-untersuchte-lymphknoten|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-anzahl-untersuchte-sentinel-lymphknoten: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-anzahl-untersuchte-sentinel-lymphknoten|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-allgemeiner-leistungszustand-ecog: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-allgemeiner-leistungszustand-ecog|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-tod: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-tod|${fhir.profiles.mii-onko-package-version}"
    mii-pr-onko-histologie-icdo3: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-histologie-icdo3|${fhir.profiles.mii-onko-package-version}"
  display:
    histologyLoinc: "Histology and Behavior ICD-O-3 Cancer"
    gradingLoinc: "Grade pathology value Cancer"
    tnmcLoinc: "Stage group.clinical Cancer"
    tnmpLoinc: "Stage group.pathology Cancer"
    fernMetaLoinc: "Distant metastases.clinical"
    deathLoinc: "Primary cause of death"
    gleasonScoreSct: "Gleason score (observable entity)"
    gleasonScoreLoinc: "Gleason score in Specimen Qualitative"
    psaLoinc: "Prostate specific Ag [Mass/volume] in Serum or Plasma"
  url:
    tnmPraefix: "http://dktk.dkfz.de/fhir/StructureDefinition/onco-core-Extension-TNMcpuPraefix"
  mappings:
    modul:
      prostata:
        enabled: false
